In [4]:
import numpy as np
import torch

## 초기화 방법 1. 내가 값 지정하기

In [5]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)

In [6]:
x_data

tensor([[1, 2],
        [3, 4]])

In [12]:
x_data.dtype

torch.int64

## 초기화 방법 2. 랜덤 값 사용

In [14]:
shape = (2,3)
rand_tensor = torch.rand(shape)
print(f"Random Tensor: \n {rand_tensor}\n")

ones_tensor = torch.ones(shape)
print(f"Random Tensor: \n {ones_tensor}\n")

zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {zeros_tensor}\n")

Random Tensor: 
 tensor([[0.6336, 0.5017, 0.0399],
        [0.2220, 0.8609, 0.1554]])

Random Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Random Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



## CIFAR10 데이터셋 불러오기
1. root = dataset 받을 위치
2. train = train 데이터셋인지 test 데이터셋인지
3. download = 다운로드 받을거니
4. transform = 이미지를 어떻게 transform 할거니

In [15]:
#import library
import numpy as np
import torch
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt
import os

In [17]:
#cache 폴더 생성
os.makedirs("../.cache", exist_ok=True)

In [18]:
#데이터셋 불러오기
training_data = datasets.CIFAR10(
    root="../.cache",
    train=True,
    download=True,
    transform=ToTensor()
)

100%|██████████████████████████████████████████████| 170M/170M [00:49<00:00, 3.47MB/s]


Extracting ../.cache\cifar-10-python.tar.gz to ../.cache


In [19]:
test_data = datasets.CIFAR10(
    root="../.cache",
    train=False,
    download=True,
    transform=ToTensor()
)

Files already downloaded and verified
